### ISSUE TITLE
Weird Behavior in SHMS Aerogel Negative Pedestals, ADC Channels 1-6

### ISSUE THREAD

**Issue by Yero1990** [JeffersonLab/hallc_replay#121]
While inspecting the onlineGUI Histograms for SHMS Aerogel, I noticed a wierd pattern in SHMS
AEROGEL Chanels (1-6)+ Pulse Pedestals. (See Figures  [paero_1_6+.pdf](https://github.com/JeffersonLab/hallc_replay/files/956061/paero_1_6.pdf) and [shms_aero2+.pdf](https://github.com/JeffersonLab/hallc_replay/files/956063/shms_aero2.pdf) )

I went to the Counting Room to examine these channels, and it happened that the 'problematic channels'
originate from SHMS Crate 2, ADC SLOT10. Eric and I also examined Channels from the QUARTZ that were also from this ADC, and they showed a similar pattern in the pedestals. It seems that there might be
something going on with this FLASH ADC.    What is your input on this, Brad?

**Comment by pooser** [comment]
@sawatzky

**Comment by pooser** [comment]
@sawatzky I would like to look at the FADC thresholds that were set for ROC2 SLOT 10 during the KPP runs.  However, it appears that the 'coda' user account and cdaqfs filesystem no longer has the directory "/net/cdaqfs/home/coda/coda/thresholds/".  Have the threshold files moved to another location?

**Comment by pooser** [comment]
I decoded some FADC data from the SHMS run 488 and found two identical events in SLOT 9 and 10.  At first glance there does not appear to be a smoking gun....yet!

Fadc250Module::Decode:: Slot from FADC block header = 10
Fadc250Module::Decode:: FADC BLOCK HEADER >> data = 82841401 >> slot = 10 >> module id = 1 >> event block number = 20 >> num events in block = 1
Fadc250Module::Decode:: FADC DATA TYPES >> data = 92800014 >> data word id = 1 >> data type = 2
Fadc250Module::Decode:: FADC EVENT HEADER >> data = 92800014 >> event header trigger time = 0 >> trigger number = 20
Fadc250Module::Decode:: FADC DATA TYPES >> data = 9c9b4400 >> data word id = 1 >> data type = 3
Fadc250Module::Decode:: FADC TRIGGER TIME >> data = 9c9b4400 >> trigger time word 1 = 10175488 >> trigger time word 2 = 105 >> trigger time = 1771783168
Fadc250Module::Decode:: FADC DATA TYPES >> data = 69 >> data word id = 0 >> data type = 3
Fadc250Module::Decode:: FADC TRIGGER TIME >> data = 69 >> trigger time word 1 = 10175488 >> trigger time word 2 = 105 >> trigger time = 1771783168
Fadc250Module::Decode:: FADC DATA TYPES >> data = c80b096c >> data word id = 1 >> data type = 9
Fadc250Module::Decode:: FADC PULSE PARAMETERS >> data = c80b096c >> chan = 6 >> event of block = 1 >> quality factor = 0 >> pedestal sum = 2412
Fadc250Module::Decode:: FADC DATA TYPES >> data = 4461b007 >> data word id = 0 >> data type = 9
Fadc250Module::Decode:: FADC PULSE PARAMETERS >> data = 4461b007 >> chan = 6 >> integral = 17947 >> nsa extended = 0 >> sample overflow = 0 >> sample underflow = 0 >> sample over threshold = 7
Fadc250Module::Decode:: FADC DATA TYPES >> data = 30e1748 >> data word id = 0 >> data type = 9
Fadc250Module::Decode:: FADC PULSE PARAMETERS >> data = 30e1748 >> chan = 6 >> coarse time = 24 >> fine time = 28 >> time = 1564 >> pulse peak = 745 >> peak beyond nsa = 0 >> peak not found = 0 >> peak above maxped = 0
Fadc250Module::Decode:: FADC DATA TYPES >> data = 8a800008 >> data word id = 1 >> data type = 1
Fadc250Module::Decode:: FADC BLOCK TRAILER >> data = 8a800008 >> slot = 10 >> nwords in block = 8


Fadc250Module::Decode:: Slot from FADC block header = 9
Fadc250Module::Decode:: FADC BLOCK HEADER >> data = 82441201 >> slot = 9 >> module id = 1 >> event block number = 18 >> num events in block = 1
Fadc250Module::Decode:: FADC DATA TYPES >> data = 92446012 >> data word id = 1 >> data type = 2
Fadc250Module::Decode:: FADC EVENT HEADER >> data = 92446012 >> event header trigger time = 70 >> trigger number = 18
Fadc250Module::Decode:: FADC DATA TYPES >> data = 99979c46 >> data word id = 1 >> data type = 3
Fadc250Module::Decode:: FADC TRIGGER TIME >> data = 99979c46 >> trigger time word 1 = 9935942 >> trigger time word 2 = 105 >> trigger time = 1771543622
Fadc250Module::Decode:: FADC DATA TYPES >> data = 69 >> data word id = 0 >> data type = 3
Fadc250Module::Decode:: FADC TRIGGER TIME >> data = 69 >> trigger time word 1 = 9935942 >> trigger time word 2 = 105 >> trigger time = 1771543622
Fadc250Module::Decode:: FADC DATA TYPES >> data = c80a8831 >> data word id = 1 >> data type = 9
Fadc250Module::Decode:: FADC PULSE PARAMETERS >> data = c80a8831 >> chan = 5 >> event of block = 1 >> quality factor = 0 >> pedestal sum = 2097
Fadc250Module::Decode:: FADC DATA TYPES >> data = 43baf001 >> data word id = 0 >> data type = 9
Fadc250Module::Decode:: FADC PULSE PARAMETERS >> data = 43baf001 >> chan = 5 >> integral = 15279 >> nsa extended = 0 >> sample overflow = 0 >> sample underflow = 0 >> sample over threshold = 1
Fadc250Module::Decode:: FADC DATA TYPES >> data = 30b9140 >> data word id = 0 >> data type = 9
Fadc250Module::Decode:: FADC PULSE PARAMETERS >> data = 30b9140 >> chan = 5 >> coarse time = 24 >> fine time = 23 >> time = 1559 >> pulse peak = 552 >> peak beyond nsa = 0 >> peak not found = 0 >> peak above maxped = 0
Fadc250Module::Decode:: FADC DATA TYPES >> data = 8a400008 >> data word id = 1 >> data type = 1
Fadc250Module::Decode:: FADC BLOCK TRAILER >> data = 8a400008 >> slot = 9 >> nwords in block = 8

**Comment by sawatzky** [comment]
Threshold files are found here:
  /home/coda/coda/config_files/<arm>/ROC0n/thresholds.dat

-- Brad

**Comment by pooser** [comment]
See the following logbook entries for reference:

https://logbooks.jlab.org/entry/3471326

https://logbooks.jlab.org/entry/3471398
